apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-db-mongodb-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.1.74
    path: /srv/k8s-shared/db/mongodb
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-db-postgres-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.1.74
    path: /srv/k8s-shared/db/postgres
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-db-qdrant-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.1.74
    path: /srv/k8s-shared/db/qdrant
    readOnly: false
