apiVersion: v1
kind: Service
metadata:
  name: hg-chatbot-service
  namespace: hg-chatbot
  labels:
    app: hg-chatbot
spec:
  type: NodePort
  selector:
    app: hg-chatbot
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 30888
    protocol: TCP
    name: http
